@startuml

actor Usuario

usecase "Agregar Producto" as UC1
usecase "Eliminar Producto" as UC2
usecase "Ver Lista de Productos" as UC3
usecase "Cambiar Modo Oscuro" as UC4
usecase "Cambiar Idioma" as UC5

Usuario --> UC1
Usuario --> UC2
Usuario --> UC3
Usuario --> UC4
Usuario --> UC5

@enduml

